<?php

/**
 * @file
 * Contains udn_login.module.
 */
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function udn_login_theme() {
  return [
    'html__user__login' => [
      'base hook' => 'html',
    ],
    'page__user__login' => [
      'base hook' => 'page'
    ],
    'user_login_form' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function udn_login_page_attachments_alter(array &$attachments) {
  if ("user.login" === \Drupal::routeMatch()->getRouteName()) {
    unset($attachments['#attached']['library']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function udn_login_preprocess_page__user__login(array &$variables) {
  $page = &$variables['page'];
  foreach (Element::children($page) as $region) {
    if ($region != 'content') {
      unset($page[$region]);
    }
  }

  $content_block = \Drupal::theme()->getActiveTheme()->getName() . '_content';
  $content_region = &$variables['page']['content'];
  foreach (Element::children($content_region) as $block) {
    if ($block != $content_block) {
      unset($content_region[$block]);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function udn_login_preprocess_user_login_form(array &$variables) {
  $element = &$variables['element'];
  unset($element['name']['#theme_wrappers']);
  unset($element['pass']['#theme_wrappers']);
}

